name: 'momo_org'
version: 1.0.0
config-version: 2

models:
  momo_org:
    staging:
      +materialized: view
      +on_schema_change: sync_all_columns
    mart:
      +materialized: table
      +on_schema_change: sync_all_columns

    
    
