WITH cleaned AS (
SELECT 
    COALESCE(TRIM(URL), 'NA') AS URL,
    COALESCE(TRIM(DATE), 'DD-MM-YYYY') AS DATE,
    COALESCE(TRIM(TITLE), 'NA') AS TITLE,
    COALESCE(TRIM(ARTIST), 'NA') AS ARTIST,
    COALESCE(TRIM(GENDER), 'NA') AS GENDER,
    COALESCE(TRIM(MEDIUM), 'NA') AS MEDIUM,
    COALESCE(TRIM(ONVIEW), 'NA') AS ONVIEW,

    ABS(COALESCE(TRY_CAST(TRIM(ENDDATE) AS INT), 0)) AS "END_DATE",

    COALESCE(TRIM(IMAGEURL), 'NA') AS IMAGEURL,

    COALESCE(TRY_CAST(TRIM(OBJECTID) AS INT), 0) AS "OBJECT_ID",

    COALESCE(TRIM(ARTISTBIO), 'NA') AS "ARTIST_BIO",

    ABS(COALESCE(TRY_CAST(TRIM(BEGINDATE) AS INT), 0)) AS ""BEGIN_DATE",

    COALESCE(TRIM(CATALOGED), 'NA') AS CATALOGED,
    COALESCE(TRIM(CREDITLINE), 'NA') AS CREDITLINE,
    COALESCE(TRIM(DEPARTMENT), 'NA') AS DEPARTMENT,

    COALESCE(TRIM("DEPTH (CM)"), 'NA') AS "DEPTH_CM",
    COALESCE(TRIM(DIMENSIONS), 'NA') AS DIMENSIONS,

    COALESCE(TRY_CAST(TRIM("WIDTH (CM)") AS NUMERIC(10,6)), 0) AS "WIDTH_CM",
    COALESCE(TRY_CAST(TRIM("HEIGHT (CM)") AS NUMERIC(10,6)), 0) AS "HEIGH_CM",
    COALESCE(TRY_CAST(TRIM("LENGTH (CM)") AS NUMERIC(10,6)), 0) AS "LENGTH_CM",

    COALESCE(TRIM(NATIONALITY), 'NA') AS NATIONALITY,

    COALESCE(TRY_CAST(TRIM("WEIGHT (KG)") AS NUMERIC(10,6)), 0) AS "WEIGHT_KG",

    COALESCE(TRY_CAST(TRIM(DATEACQUIRED) AS DATE), DATE '1900-01-01') AS DATEACQUIRED,

    COALESCE(TRY_CAST(TRIM(CONSTITUENTID) AS INT), 0) AS CONSTITUENT_ID,

    COALESCE(TRY_CAST(TRIM("DIAMETER (CM)") AS NUMERIC(10,6)), 0) AS "DIAMETER_CM",

    COALESCE(TRIM(CLASSIFICATION), 'NA') AS CLASSIFICATION,
    COALESCE(TRIM(ACCESSIONNUMBER), 'NA') AS "ACCESSION_NUMBER",

    COALESCE(TRY_CAST(TRIM("DURATION (SEC.)") AS NUMERIC(10,6)), 0) AS "DURATION_SEC",
    COALESCE(TRY_CAST(TRIM("SEAT HEIGHT (CM)") AS NUMERIC(10,6)), 0) AS "SEAT HEIGHT_CM",
    COALESCE(TRY_CAST(TRIM("CIRCUMFERENCE (CM)") AS NUMERIC(10,6)), 0) AS "CIRCUMFERENCE_CM"

FROM {{ source('source_moma', 'SHEET1') }}
)

SELECT * FROM cleaned;
