WITH cleaned AS (
SELECT 
    COALESCE(TRIM(URL), 'NA') AS URL,
    COALESCE(TRIM(DATE), 'DD-MM-YYYY') AS DATE,
    COALESCE(TRIM(TITLE), 'NA') AS TITLE,
    COALESCE(TRIM(ARTIST), 'NA') AS ARTIST,
    COALESCE(TRIM(GENDER), 'NA') AS GENDER,
    COALESCE(TRIM(MEDIUM), 'NA') AS MEDIUM,
    COALESCE(TRIM(ONVIEW), 'NA') AS ONVIEW,

    ABS(COALESCE(TRY_CAST(TRIM(ENDDATE) AS INT), 0)) AS ENDDATE,

    COALESCE(TRIM(IMAGEURL), 'NA') AS IMAGEURL,

    COALESCE(TRY_CAST(TRIM(OBJECTID) AS INT), 0) AS OBJECTID,

    COALESCE(TRIM(ARTISTBIO), 'NA') AS ARTISTBIO,

    ABS(COALESCE(TRY_CAST(TRIM(BEGINDATE) AS INT), 0)) AS BEGINDATE,

    COALESCE(TRIM(CATALOGED), 'NA') AS CATALOGED,
    COALESCE(TRIM(CREDITLINE), 'NA') AS CREDITLINE,
    COALESCE(TRIM(DEPARTMENT), 'NA') AS DEPARTMENT,

    COALESCE(TRIM("DEPTH (CM)"), 'NA') AS "DEPTH (CM)",
    COALESCE(TRIM(DIMENSIONS), 'NA') AS DIMENSIONS,

    COALESCE(TRY_CAST(TRIM("WIDTH (CM)") AS NUMERIC(10,6)), 0) AS "WIDTH (CM)",
    COALESCE(TRY_CAST(TRIM("HEIGHT (CM)") AS NUMERIC(10,6)), 0) AS "HEIGHT (CM)",
    COALESCE(TRY_CAST(TRIM("LENGTH (CM)") AS NUMERIC(10,6)), 0) AS "LENGTH (CM)",

    COALESCE(TRIM(NATIONALITY), 'NA') AS NATIONALITY,

    COALESCE(TRY_CAST(TRIM("WEIGHT (KG)") AS NUMERIC(10,6)), 0) AS "WEIGHT (KG)",

    COALESCE(TRY_CAST(TRIM(DATEACQUIRED) AS DATE), DATE '1900-01-01') AS DATEACQUIRED,

    COALESCE(TRY_CAST(TRIM(CONSTITUENTID) AS INT), 0) AS CONSTITUENTID,

    COALESCE(TRY_CAST(TRIM("DIAMETER (CM)") AS NUMERIC(10,6)), 0) AS "DIAMETER (CM)",

    COALESCE(TRIM(CLASSIFICATION), 'NA') AS CLASSIFICATION,
    COALESCE(TRIM(ACCESSIONNUMBER), 'NA') AS ACCESSIONNUMBER,

    COALESCE(TRY_CAST(TRIM("DURATION (SEC.)") AS NUMERIC(10,6)), 0) AS "DURATION (SEC.)",
    COALESCE(TRY_CAST(TRIM("SEAT HEIGHT (CM)") AS NUMERIC(10,6)), 0) AS "SEAT HEIGHT (CM)",
    COALESCE(TRY_CAST(TRIM("CIRCUMFERENCE (CM)") AS NUMERIC(10,6)), 0) AS "CIRCUMFERENCE (CM)"

FROM {{ source('source_moma', 'SHEET1') }}
)

SELECT * FROM cleaned;
